export const LOAD_ALL_COINS = "LOAD_ALL_COINS";
export const USD_CURRENCY = "USD_CURRENCY";
export const GET_NUMBER_OF_ALL_COINS = "GET_NUMBER_OF_ALL_COINS";
export const GET_NUMBER_OF_ALL_EXCHANGES = "GET_NUMBER_OF_ALL_EXCHANGES";
