export const LOAD_ALL_COINS = "LOAD_ALL_COINS";
export const USD_CURRENCY = "USD_CURRENCY";
export const GET_NUMBER_OF_ALL_COINS = "GET_NUMBER_OF_ALL_COINS";
export const GET_NUMBER_OF_ALL_EXCHANGES = "GET_NUMBER_OF_ALL_EXCHANGES";
export const GET_GLOBAL_DATA = "GET_GLOBAL_DATA";
export const TOP_TRENDING_COINS = "TOP_TRENDING_COINS";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const CHANGE_PAGE_COINS = "CHANGE_PAGE_COINS";

