export const LOAD_ALL_COINS = "LOAD_ALL_COINS";
export const USD_CURRENCY = "USD_CURRENCY";
export const GET_NUMBER_OF_ALL_COINS = "GET_NUMBER_OF_ALL_COINS";
export const GET_NUMBER_OF_ALL_EXCHANGES = "GET_NUMBER_OF_ALL_EXCHANGES";
export const GET_GLOBAL_DATA = "GET_GLOBAL_DATA";
export const TOP_TRENDING_COINS = "TOP_TRENDING_COINS";
export const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const CHANGE_PAGE_COINS = "CHANGE_PAGE_COINS";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";
export const PREVIOUS_PAGE_BOOL = "PREVIOUS_PAGE_BOOL";
export const SET_LOADING = "SET_LOADING";
export const SET_SINGLE_COIN = "SET_SINGLE_COIN";
export const SET_SEARCH_INPUT_VALUE = "SET_SEARCH_INPUT_VALUE";


